services:
  emqx:
    image: emqx/emqx:latest
    ports:
      - "1883:1883"  # MQTT port
      - "8083:8083"  # Dashboard port

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - influxdb_data:/var/lib/influxdb

volumes:
  influxdb_data:
