version: '3.8'
services:
  emqx:
    image: emqx/emqx:latest
    container_name: emqx
    ports:
      - "1883:1883"    # MQTT port
      - "8081:8081"    # Management Dashboard port
    environment:
      - EMQX_LOADED_PLUGINS="emqx_management,emqx_dashboard"
